name: Build & Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Manager Agent
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: ./app/Dockerfile
          push: true
          tags: painaidee/manager-agent:latest

      - name: Build and push Technical Agent
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: ./Technical_Agent/Dockerfile
          push: true
          tags: painaidee/technical-agent:latest

      - name: Build and push Fundamental Agent
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: ./Fundamental_Agent/Dockerfile
          push: true
          tags: painaidee/fundamental-agent:latest

      - name: Build and push Database Agent
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: ./Database_Agent/Dockerfile
          push: true
          tags: painaidee/database-agent:latest
