name: Build & Push All Agents

on:
  push:
    branches: [main]

jobs:
  build-and-push-agents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Manager Agent
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: painaidee/manager-agent:latest

      - name: Build & Push Technical Agent
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.technical
          push: true
          tags: painaidee/technical-agent:latest

      - name: Build & Push Fundamental Agent
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.fundamental
          push: true
          tags: painaidee/fundamental-agent:latest
